// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADs3IZn5lwS36WxBozm31OXtSN0WQlV7I',
    appId: '1:788838965440:web:7edc2c82bd69bc0957cd25',
    messagingSenderId: '788838965440',
    projectId: 'chronos-protos-nome',
    authDomain: 'chronos-protos-nome.firebaseapp.com',
    storageBucket: 'chronos-protos-nome.appspot.com',
    measurementId: 'G-2TRKPYPSDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFNWKvpbF-HK-lGJwUrKW9SfCv_TVolY',
    appId: '1:788838965440:android:bf25553c8e54dce857cd25',
    messagingSenderId: '788838965440',
    projectId: 'chronos-protos-nome',
    storageBucket: 'chronos-protos-nome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvDT5L5TroDZUU_BbAiHrb0VAkPjNnGsU',
    appId: '1:788838965440:ios:163bbb7c28c30fcf57cd25',
    messagingSenderId: '788838965440',
    projectId: 'chronos-protos-nome',
    storageBucket: 'chronos-protos-nome.appspot.com',
    iosClientId:
        '788838965440-3qo2ajo6dgue9eefac8qq1d7a64e55r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.metronome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvDT5L5TroDZUU_BbAiHrb0VAkPjNnGsU',
    appId: '1:788838965440:ios:163bbb7c28c30fcf57cd25',
    messagingSenderId: '788838965440',
    projectId: 'chronos-protos-nome',
    storageBucket: 'chronos-protos-nome.appspot.com',
    iosClientId:
        '788838965440-3qo2ajo6dgue9eefac8qq1d7a64e55r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.metronome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvDT5L5TroDZUU_BbAiHrb0VAkPjNnGsU',
    appId: '1:788838965440:ios:163bbb7c28c30fcf57cd25',
    messagingSenderId: '788838965440',
    projectId: 'chronos-protos-nome',
    storageBucket: 'chronos-protos-nome.appspot.com',
  );
}
