# This workflow uses actions to run project test
# It should run every time there's a pull request

name: Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Updating dependencies
      run: flutter pub get
    - name: Running tests
      run: flutter test
